/* SPDX-License-Identifier: MIT */
#ifndef WIRE_PROBE_H
#define WIRE_PROBE_H

/*
 * Sensing-wire break detection for 4 channels.
 *
 * The implementation is provided as a prebuilt library
 * (Core/Lib/libwireprobe.a). This header only describes the interface.
 *
 * Dependencies: hadc1, htim1, htim3 generated by CubeMX; app_wwdg_kick() provided by the application.
 */

#include <stdint.h>
#include <stdbool.h>

#define PROBE_CHANNELS          4
#define PROBE_OPEN_MVPP_DEFAULT 450   /* default threshold when flash has no config */

typedef enum { PROBE_UNKNOWN = 0, PROBE_CLOSED, PROBE_OPEN } probe_state_t;

/* Field order and types must not change — they must match the library. */
typedef struct {
  uint16_t amp_cnt;    /* measured amplitude (ADC counts) */
  uint16_t mvpp;       /* measured amplitude (mVpp) — exported to a Modbus register */
  uint16_t mean;       /* diagnostics */
  uint16_t min;        /* diagnostics */
  uint16_t max;        /* diagnostics */
} probe_result_t;

/* Initialise the wire-check hardware. Call after MX_*_Init. */
void probe_init(void);

/* Measure one channel 0..3 (M1..M4). Returns false if the ADC does not respond. */
bool probe_measure(int ch, probe_result_t *r);

/* Set the wire-break threshold (wire= command) — effective from the next measurement. */
void probe_set_open_mvpp(uint16_t mvpp);

/* Update the state of channel ch with a new result; returns the confirmed state. */
probe_state_t probe_update(int ch, const probe_result_t *r);

/* Labels: "WIRE NG" (broken/open), "WIRE OK" (connected), "?" (not yet confirmed) */
const char *probe_state_str(probe_state_t s);

#endif /* WIRE_PROBE_H */
